version: '3.9'

services:
  mongodb-rs:
    container_name: mongodb-rs
    build:
      context: ./db
      # dockerfile: ./db/Dockerfile
    env_file:
      - ./db/.env
    ports:
      - 27017:27017
    # restart: unless-stopped
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      # ME_CONFIG_MONGODB_ENABLE_ADMIN: 1
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongodb-rs:27017/?authSource=admin
    depends_on:
    - mongodb-rs
